### ISSUE TITLE
Problem with bootstrap-treeview folder

### ISSUE THREAD

**Issue by Maxcorp** [execut/yii2-widget-bootstraptreeview#10]
Hello!

You've changed repository in commit https://github.com/execut/yii2-widget-bootstraptreeview/commit/c3c2045f552f8a492cd5f103a2cf28cf32343d12

But, you didn't change source path here https://github.com/execut/yii2-widget-bootstraptreeview/blob/master/TreeViewBowerAsset.php#L13

Without change, we have an error "The file or directory to be published does not exist: \vendor\bower/bootstrap-treeview/dist".

**Comment by execut** [comment]
Thanks for report! My bower folder was not cleaned, so everything worked fine. I fix it in new version.
