### ISSUE TITLE
AdminLTE & jquery-ui

### ISSUE THREAD

**Issue by letsjump** [execut/yii2-widget-bootstraptreeview#12]
Your plugin implementation is loading jquery-ui, which add some css classes to every bootstrap button and create some strange layout issues (bigger button fonts, paddings, and so on).
Is there a way to disable this behaviour by disabling jquery-ui that seems to be not required by the original johnmiles plugin?

**Comment by execut** [comment]
Hello! Jquery UI is only needed for TreeFilterInput. You can disable it by specifying a parameter template:
```php
echo TreeView::widget([
    'template' => TreeView::TEPLATE_SIMPLE
]);
```
I deleted now ui when it is not needed: https://github.com/execut/yii2-widget-bootstraptreeview/commit/87b42493dca1d61caac52003ef871bf7593279c0
Update the package to new version. Thank you for your note!
