### ISSUE TITLE
links

### ISSUE THREAD

**Issue by TrueGameover** [execut/yii2-widget-bootstraptreeview#15]
There is problem with links support. Your project uses patternfly-bootstrap-treeview, but this fork doesn't support links as jonmiles/bootstrap-treeview. (links == href)

**Comment by execut** [comment]
Hello! Do you have a broken example? [Does this work?](https://github.com/execut/yii2-widget-bootstraptreeview/blob/master/examples/example-pjax-navigation.php)
Everything works for me with the href parameters
