### ISSUE TITLE
yii\base\BaseObject not found

### ISSUE THREAD

**Issue by Taroxx** [execut/yii2-widget-bootstraptreeview#19]
I have this problem after install by composer and try demo simple example.
```
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'yii\base\BaseObject' not found' 

in /var/www/taroxx/vendor/execut/yii2-base/jui/widget/Helper.php:16

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```
yii2-app-advanced v2.0.4
yii2-jui v2.0.7

**Comment by execut** [comment]
Hello! Problem in old version yii2. Package execut/yii2-base required "yiisoft/yii2": ">=2.0.13". Try update yii2

**Comment by Taroxx** [comment]
Thanks. But maybe I can try to rename `use yii\base\BaseObject` to `use yii\base\Object`, and other same classes to old version of names?

PS  `use yii\base\BaseObject` to `use yii\base\Object`  work, but I had exception at next class.

**Comment by execut** [comment]
Rename is not a very elegant solution.
You can try downgrade execut/yii2-base to version 1.5.2 without BaseObject. But I can not guarantee the correct work yii2-widget-bootstraptreeview.

**Comment by Taroxx** [comment]
Ok. Thanks. I will try it)

**Comment by Taroxx** [comment]
Привет. Я обновил yii до версии 2.0.21.
Теперь вылетает вот такая ошибка

```
Exception 'yii\base\InvalidArgumentException' with message 'The file or directory to be published does not exist: /var/www/taroxx/vendor/bower/patternfly-bootstrap-treeview/dist' 

in /var/www/taroxx/vendor/yiisoft/yii2/web/AssetManager.php:455
```

**Comment by execut** [comment]
Привет! Стоит плагин https://packagist.org/packages/fxp/composer-asset-plugin ? Вроде проблема с его настройкой. Сейчас сделали новый способ работы с NPM, через улучшенный composer:
https://asset-packagist.org/
Нужно сделать 3 шага, чтобы перейти на него:

1. Удалить fxp/composer-asset-plugin
1. Добавить в composer.json:
```
"repositories": [
    {
        "type": "composer",
        "url": "https://asset-packagist.org"
    }
]
```
3. Запустить ./composer.phar update

**Comment by execut** [comment]
Ещё можно попробовать добавить алиасы путей в конфиг приложения:
```php
'aliases' => [
    '@bower' => '@vendor/bower-asset',
    '@npm'   => '@vendor/npm-asset',
],
```

**Comment by Taroxx** [comment]
Странно, но у меня и fxp/composer-asset-plugin есть и в composer есть

```
"repositories": [
    {
        "type": "composer",
        "url": "https://asset-packagist.org"
    }
]
```
И видимо поэтому в папке vendor две директории bower и bower-asset.

Сейчас попробую алиасы прописать.

**Comment by Taroxx** [comment]
Отлично. Алиасы сработали. Спасибо!

**Comment by execut** [comment]
Пожалуйста!
