### ISSUE TITLE
composer update error

### ISSUE THREAD

**Issue by stepan-chircioglo** [execut/yii2-widget-bootstraptreeview#5]
Раньше проблем не было, а сейчас вот такая ошибка. Подскажите, в чем проблема?

http://joxi.ru/brRD6v4iVq7G21

**Comment by execut** [comment]
Похоже у вас стоит флаг стабильности minimum-stability stable
Не подумал, когда ставил версию yii2-base 0.0.2, похоже композер считает её не стабильной. Попробуйте сейчас, поставил 1.0.2

**Comment by stepan-chircioglo** [comment]
Не понимаю, сейчас выдает ошибка " The requested package execut/yii2-widget-bootstraptreeview could not be found in any version, there may be a typo in the package name."

http://joxi.ru/MAj0ljKcZNkome

**Comment by stepan-chircioglo** [comment]
Испробовал всякие способы, пока ничего не помогло, как и прежде проблема с yiibase,

http://joxi.ru/v29QlVZcQgRX2G

**Comment by execut** [comment]
Вроде починил. На локалке получилось поставить пакет с такими настройками:

``` javascript
{
  "name": "yiisoft/yii2-app-advanced",
  "description": "Yii 2 Advanced Application Template",
  "keywords": ["yii2", "framework", "advanced", "application template"],
  "homepage": "http://www.yiiframework.com/",
  "type": "project",
  "license": "BSD-3-Clause",
  "support": {
    "issues": "https://github.com/yiisoft/yii2/issues?state=open",
    "forum": "http://www.yiiframework.com/forum/",
    "wiki": "http://www.yiiframework.com/wiki/",
    "irc": "irc://irc.freenode.net/yii",
    "source": "https://github.com/yiisoft/yii2"
  },
  "minimum-stability": "stable",
  "discard-changes": true,
  "require": {
    "php": ">=5.4.0",
    "execut/yii2-widget-bootstraptreeview": "dev-master"
  },
  "extra": {
    "asset-installer-paths": {
      "npm-asset-library": "vendor/npm",
      "bower-asset-library": "vendor/bower"
    }
  }
}

```

 Проблема была в версиях. Нужно было веток насоздавать, чтобы композер видел стабильные версии.
А у вас как?

**Comment by stepan-chircioglo** [comment]
Теперь все супер, спасибо, все работает!
Хорошее приложение...

**Comment by execut** [comment]
Пожалуйста! Теперь хоть узнал что такое версии в композере=)
