### ISSUE TITLE
Count number

### ISSUE THREAD

**Issue by f1dz** [execut/yii2-widget-bootstraptreeview#7]
Hi @execut, how do you put the number on the right of leafs?

**Comment by execut** [comment]
Hi! Image taken from example Jonmiles widget. I think it's bootstrap badges, enabled by pass tags attribute to javascript widget:
[https://github.com/jonmiles/bootstrap-treeview#tags](https://github.com/jonmiles/bootstrap-treeview#tags)
[http://getbootstrap.com/components/#badges](http://getbootstrap.com/components/#badges)
This can be done by passing tags option to item config

```
$data = [
    [
        'text' => 'Item with badge',
        'tags' => ['42'],
    ]
];
```
