### ISSUE TITLE
Не переопределить параметр "data".

### ISSUE THREAD

**Issue by ivan-cc** [execut/yii2-widget-bootstraptreeview#8]
Хочу подгружать содержимое дерева аяксом, но виджет принудительно указывает в параметрах bootstrap-treeview свои значения параметра data, а хочется его переопределить через:
`        'clientOptions' => [
            'data' => 'getTree();'
]`

**Comment by execut** [comment]
Покопался в документации https://github.com/jonmiles/bootstrap-treeview, похоже этот js-виджет не умеет динамично менять свою структуру. Можно просто перезагружать блок с yii2-виджетом
